# Generated by Django 5.2.6 on 2025-11-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('students_enrolled', models.PositiveIntegerField(default=0)),
                ('graduation_rate', models.FloatField(default=0.0)),
                ('expert_faculty', models.PositiveIntegerField(default=0)),
                ('mission_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MySchool', max_length=100)),
                ('about_text', models.TextField(help_text='Short footer description text.')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('button_text1', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link1', models.URLField(blank=True, null=True)),
                ('button_text2', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link2', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='news/')),
                ('read_more_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Student Life', max_length=100)),
                ('headline', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='student_life/')),
                ('sub_image1', models.ImageField(blank=True, null=True, upload_to='student_life/')),
                ('sub_image2', models.ImageField(blank=True, null=True, upload_to='student_life/')),
                ('link_text', models.CharField(default='Explore Student Life', max_length=100)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Studio', 'Services', 'Resources', 'Connect'", max_length=100)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main_app.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main_app.footerlinkcategory')),
            ],
        ),
    ]
