# Generated by Django 5.2.6 on 2025-11-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='background_image',
            field=models.ImageField(upload_to='templaes/img/'),
        ),
    ]
